// simple-chat/app-fe-vue3/src/pages/components/helloModal.vue
<template>
  <Modal v-if="isShow" :close="closeModal" :options="modalOptions">
    <div class="modal">      
      <div class="modal-container">
        <div class="modal-item-1">
          <p>
            * This App save Anything Information <br />
            ** Please Input display-name
          </p>
          <p style="margin-top:50px;">
            <input 
              id="outlined-basic" 
              type="text" 
              class="MuiInputBase-input MuiOutlinedInput-input"
              v-model="name"
              ref="refModalInputName"
              @keyup.enter.up="handleClose">
            &nbsp;
            <button @click="handleClose">Enter</button>
          </p>
        </div>
        <div class="modal-item-2" title="Image From material-ui.com" style=""></div>
      </div>
    </div>
  </Modal>
</template>

<script lang="ts">
import { defineComponent, onMounted, ref } from 'vue'
import { useToast } from 'vue-toastification'

export default defineComponent({
  name: 'helloModal',
  props: ['openProps', 'closeProps'],
  setup (props) {

    const refModalInputName = ref<HTMLElement | null>(null)
    const name = ref<string>(`anyName_${(Math.random()).toFixed(4)}`)
    const modalOptions = ref<object>({closeClickDimmed: false})
    const isShow = ref<boolean>(props.openProps)

    function showModal () {
      isShow.value = true
    }
    function closeModal () {
      isShow.value = false
    }
    function handleClose () {
      if (name.value === null || name.value === '') {        
        const toast = useToast();
        toast.error('Check display-name', {
          timeout: 2000,
          hideProgressBar: true,
        })
        return
      }
      props.closeProps(name.value)
      closeModal()
    }

    onMounted(() => {
      if (refModalInputName.value) {
        refModalInputName.value.focus()
      }
    })

    return {
      name,
      isShow,
      modalOptions,
      refModalInputName,
      showModal,
      closeModal,
      handleClose
    }
  },
  methods: {
    
  }
})
</script>

<style scoped lang="scss">
.modal {
  width: 400px;
  padding: 0px;
  box-sizing: border-box;
  background-color: #fff;
  font-size: 13px;
  text-align: center;
  color: black;
}

.modal-container {
	display: flex;
	/* display: inline-flex; */

  .modal-item-1 {
    width: 250px; 
    height:160px; 
  }
  .modal-item-2 {
    width: 150px; 
    height: 160px; 
    background-image: url('https://material-ui.com/static/images/cards/live-from-space.jpg');
  }
}
</style>

// simple-chat/app-fe-react/src/pages/components/helloModal.tsx
import { makeStyles, Theme, createStyles } from '@material-ui/core/styles'
import { ChangeEvent, KeyboardEvent, useState } from 'react'
import Card from '@material-ui/core/Card'
import CardContent from '@material-ui/core/CardContent'
import CardMedia from '@material-ui/core/CardMedia'
import Typography from '@material-ui/core/Typography'
import { IconButton, Snackbar, TextField } from '@material-ui/core'
import Dialog from '@material-ui/core/Dialog'
import CheckIcon from '@material-ui/icons/Check'
import { Alert } from '@material-ui/lab'

const useStyles = makeStyles((theme: Theme) =>
  createStyles({
    root: {
      display: 'flex'
    },
    details: {
      display: 'flex',
      flexDirection: 'column',
      paddingLeft: 15,
      paddingRight: 10
    },
    content: {
      flex: '1 0 auto'

    },
    cover: {
      width: 151
    },
    controls: {
      display: 'flex',
      alignItems: 'center',
      paddingLeft: theme.spacing(1),
      paddingBottom: theme.spacing(1)
    }
  })
)

type TProps = {
  openProps: boolean
  closeProps: Function
};

const myName = `anyName_${(Math.random()).toFixed(4)}`

export default function helloModal ({ openProps, closeProps }: TProps) {
  const classes = useStyles()
  const [open, setOpen] = useState(openProps)
  const [openSnackbar, setOpenSnackbar] = useState(false)
  const [name, setName] = useState(myName)
  // const inputEl = useRef(null)

  const handleClose = () => {
    if (name === null || name === '') {
      setOpenSnackbar(true)
      return
    }
    setOpen(false)
    closeProps(name)
  }

  const handleChange = (event: ChangeEvent<HTMLInputElement>) => {
    setName(event.target.value)
  }

  const handleCloseSnackbar = () => {
    setOpenSnackbar(false)
  }

  const handleKeyUp = (e: KeyboardEvent<HTMLInputElement>) => {
    if (e.key === 'Enter') {
      handleClose()
    }
  }

  // useEffect(() => {
  //   if (inputEl.current) {
  //     inputEl.current.focus()
  //   }
  // })

  return (
    <div>
      <Snackbar open={openSnackbar} autoHideDuration={6000} onClose={handleCloseSnackbar}>
        <Alert onClose={handleCloseSnackbar} severity="error">
          Check display-name
        </Alert>
      </Snackbar>
      <Dialog
        open={open}
        onClose={handleClose}
        aria-labelledby="alert-dialog-title"
        aria-describedby="alert-dialog-description"
        disableBackdropClick={true}
      >
        <Card className={classes.root} style={{ boxShadow: 'none', height: 160 }}>
            <div className={classes.details}>
              <CardContent className={classes.content}>
                <Typography variant="subtitle2" color="textSecondary">
                  * This App save Anything Information
                  <br/>
                  ** Please Input display-name
                </Typography>
              </CardContent>
              <div className={classes.controls}>
                <TextField
                  id="outlined-basic"
                  label="Input display-name"
                  variant="outlined"
                  autoFocus={true}
                  value={name}
                  onChange={handleChange}
                  onKeyUp={handleKeyUp}
                />
                <IconButton type="button" aria-label="submit" onClick={handleClose}>
                  <CheckIcon />
                </IconButton>
              </div>
            </div>
            <CardMedia
              className={classes.cover}
              image="https://material-ui.com/static/images/cards/live-from-space.jpg"
              title="Image From material-ui.com"
            />
          </Card>
      </Dialog>
    </div>
  )
}

helloModal.defaultProps = {
  openProps: true,
  closeProps: undefined
}
