// simple-chat/app-fe-vue3/src/pages/_container.vue
<template>
  <header class="MuiPaper-root MuiAppBar-root MuiAppBar-positionFixed MuiAppBar-colorPrimary mui-fixed MuiPaper-elevation4" style="">
    <div class="MuiToolbar-root MuiToolbar-dense MuiToolbar-gutters">
      <h6 class="MuiTypography-root MuiTypography-h6 MuiTypography-colorInherit MuiTypography-noWrap">Simple Chat with Vue 3</h6>
      <!-- 
        <router-link to="/">Go to Home</router-link>
        <router-link to="/chat">Go to Chat</router-link>
       -->
    </div>
  </header>
  <main style="margin-top: 60px;">
    <div class="MuiContainer-root MuiContainer-maxWidthLg">      
      <Suspense>
        <template #default>
          <router-view></router-view>
        </template>
        <template #fallback>
          <div>Loading ...</div>
        </template>
      </Suspense>
    </div>
  </main>
  <footer>
    <span class="MuiTypography-root MuiTypography-caption MuiTypography-gutterBottom MuiTypography-alignRight">
      <p>출처 1: https://dribbble.com/shots/1818748-Appon-Chat-Widget / 출처 2: https://codepen.io/drehimself/pen/KdXwxR</p>
    </span>
  </footer>

</template>

<script lang="ts">
import { defineComponent } from 'vue'
export default defineComponent({
  name: 'Container',
})
</script>

<style>
</style>

// simple-chat/app-fe-react/src/pages/_container.tsx
import { Switch, Route } from 'react-router-dom'
import { lazy, Suspense } from 'react'
import { AppBar, Container, Toolbar, Typography } from '@material-ui/core'
import { Skeleton } from '@material-ui/lab'

const Home = lazy(() => import('./home'))

function renderLoading () {
  return (
    <div>
      <Skeleton variant="text" />
      <Skeleton variant="circle" width={40} height={40} />
      <Skeleton variant="rect" width={210} height={118} />
    </div>
  )
}

function MainContainer () {
  return (
    <>
      <AppBar position="fixed" >
        <Toolbar variant="dense">
          <Typography variant="h6" color="inherit" noWrap>
            Simple Chat with React
          </Typography>
        </Toolbar>
      </AppBar>
      <main style={{ marginTop: 60 }}>
        <Container maxWidth="lg">
          <Suspense fallback={renderLoading()}>
              <Switch>
                <Route path="/" component={Home} />
              </Switch>
            </Suspense>
        </Container>
      </main>
      <footer >
        <Typography variant="caption" align="right" gutterBottom>
          <p>출처 1: https://dribbble.com/shots/1818748-Appon-Chat-Widget / 출처 2: https://codepen.io/drehimself/pen/KdXwxR</p>
        </Typography>
      </footer>
    </>
  )
}

export default MainContainer
