// simple-paint/app-fe-react/src/views/home.tsx
import '../assets/home.scss'

function Home () {
  return (
    <>
      <div className="bg-img"></div>

      <canvas id="canvas"></canvas>

      <nav className="tools-bar">
      <div className="button button-clear" data-clear></div>
      </nav>

      <nav className="thickness-bar">
        <div className="thickness active" data-thickness="4"></div>
        <div className="thickness" data-thickness="12"></div>
        <div className="thickness" data-thickness="24"></div>
        <div className="thickness" data-thickness="48"></div>
        <div className="thickness" data-thickness="128"></div>
      </nav>

      <nav className="color-bar">
        <div className="color" data-color="#9b59b6"></div>
        <div className="color" data-color="#3498db"></div>
        <div className="color" data-color="#2ecc71"></div>
        <div className="color active" data-color="#1abc9c"></div>
        <div className="color" data-color="#f1c40f"></div>
        <div className="color" data-color="#e67e22"></div>
        <div className="color" data-color="#E73C61"></div>
      </nav>
    </>
  )
}

export default Home

// simple-paint/app-fe-vue3/src/pages/home.vue
<template>
  <div>
    <div class="bg-img"></div>

      <canvas class="canvas"></canvas>

      <nav class="tools-bar">
      <div class="button button-clear" data-clear ></div>
      </nav>

      <nav class="thickness-bar">
        <div class="thickness" data-thickness="3" ></div>
        <div class="thickness" data-thickness="5" ></div>
        <div class="thickness" data-thickness="8" ></div>
        <div class="thickness" data-thickness="15" ></div>
        <div class="thickness" data-thickness="30" ></div>
      </nav>

      <nav class="color-bar">
        <div class="color" data-color="#9b59b6" ></div>
        <div class="color" data-color="#3498db" ></div>
        <div class="color" data-color="#2ecc71" ></div>
        <div class="color" data-color="#1abc9c" ></div>
        <div class="color" data-color="#f1c40f" ></div>
        <div class="color" data-color="#e67e22" ></div>
        <div class="color" data-color="#E73C61" ></div>
      </nav>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue'
export default defineComponent({
  name: 'Home'
})
</script>

<style>

</style>
